# Generated by Django 4.2.3 on 2023-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studno', models.IntegerField()),
                ('studname', models.CharField(max_length=20)),
                ('studclass', models.IntegerField()),
                ('studaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
